### ISSUE TITLE
Trajectory planning of Seven-axis robot 

### ISSUE THREAD

**Issue by YongLD** [hetolin/SAR-Net#4]
I saw the demonstration with the baxter, and the trajectory planning of the robot arm is very smooth. 
I feel uncertain because when I planned the motion trajectory with moveit, the robot arm always obtain an unexpected trajectory.
Is it that because I added some barriers in the simulation environment? I can't figure it out.

**Comment by hetolin** [comment]
Hi, Thanks for your interest in our work. 
Dose `the robot arm always obtain an unexpected trajectory.` mean that the robot has the joint jump/flip when following the calculated cartesian trajectory?  Are you using the `set_pose_target(pose_goal)` or `cartesian_path` method in the Moveit?
Adding some barriers in the simulation environment will reduce the success rate of planning.
Or could you please provide some videos of robot arm obtaining an unexpected trajectory?

**Comment by YongLD** [comment]
` mean that the robot has the joint jump/flip when following the calculated cartesian trajectory` exactly, It means that the trajectory to get the target point is odd when I set multi-target for an action sequence.
`Are you using the set_pose_target(pose_goal) or cartesian_path method in the Moveit?`  yep I straightway used the setPoseTarget method to calculate cartesian trajectory, and I can't find the better way to restrict the baxter joint_trajectory, Is there another way to do this?

**Comment by hetolin** [comment]
For the question of `the trajectory to get the target point is odd when I set multi-target for an action sequence.`, it may because you use the `setPoseTarget` method which generates kinematically feasible but constraint-free trajectory to achieve the target goal. Some trajectory points in such a pose-unconstraint trajectory may have strange inverse kinematic solution which results in the odd behavior of the robotic arm(e.g. large joint jump/flip of the a certain joint). 
You may try to use CartesianPath method to restrict the pose of baxter's end-effector and set the `jump_threshold` parameters to avoid  large joint jump/flip. It should avoid  an unexpected trajectory, to a certain extent.

**Comment by YongLD** [comment]
@hetolin Thanks a lot！
